### ISSUE TITLE
app error

### ISSUE THREAD

**Issue by CJ-Wright** [ergs/regolith#23]
```python
Traceback (most recent call last):
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/christopher/dev/regolith/regolith/app.py", line 53, in collection_page
    coll.save(body)
AttributeError: 'dict' object has no attribute 'save'
```

**Comment by CJ-Wright** [comment]
It seems that `coll` is loaded from `json.load` into  dict but then can't be saved again.
